### ISSUE TITLE
Invalid I2C address setting for AMG8834

### ISSUE THREAD

**Issue by Siegfriedchao** [physical-computation/Warp-firmware#26]
Currently, the i2c address for AMG8834 is set as `0x3A`. The sensor talks with an address of `0x68`.

**Comment by phillipstanleymarbell** [comment]
This is now addressed. Please add a comment with a reference to the issue(s) in which it was addressed.

**Comment by Siegfriedchao** [comment]
This address issue has been addressed in Pull Request issue #28.
