### ISSUE TITLE
Non mathcing type for menuI2cPullupValue variable

### ISSUE THREAD

**Issue by btsouts** [physical-computation/Warp-firmware#49]
Inside the sensor device drivers, menuI2cPullupValue variable has non-matching type declarations in different functions.

Example from devMMA8451Q.c : 

WarpStatus
configureSensorMMA8451Q(uint8_t payloadF_SETUP, uint8_t payloadCTRL_REG1, uint8_t menuI2cPullupValue)

and 

WarpStatus
writeSensorRegisterMMA8451Q(uint8_t deviceRegister, uint8_t payload, uint16_t menuI2cPullupValue)

**Comment by phillipstanleymarbell** [comment]
I believe this is completed. Moving to Verify.
