### ISSUE TITLE
j command reading the BMX055 only produces valid values the first time around.

### ISSUE THREAD

**Issue by JamesTimothyMeech** [physical-computation/Warp-firmware#57]
j command reading the BMX055 only produces valid values the first time around. The second time I try to run it I get dashes instead of the numbers that I expect. Resetting the Warp board resolves the issue but only for one round of samples.

**Comment by phillipstanleymarbell** [comment]
Is this still an issue? Kindly verify

**Comment by JamesTimothyMeech** [comment]
Fixed in #60
