### ISSUE TITLE
CSS811 Register 0x06

### ISSUE THREAD

**Issue by JamesTimothyMeech** [physical-computation/Warp-firmware#78]
**Describe the bug**
We currently only read 2 hex bytes from register 0x06 on the CSS811 and print them with the z command. 
The datasheet suggests that there are four bytes (two for vref anf two for a negative temperature coefficient sensor) to be read and all of them are needed to calculate the temperature see page 20: https://cdn.sparkfun.com/assets/learn_tutorials/1/4/3/CCS811_Datasheet-DS000459.pdf

**To reproduce**
See only two hex bytes printed in: https://github.com/physical-computation/Warp-data-stream/tree/master/data

**Expected behavior**
All four bytes should be printed to allow temperature calculation

**Comment by phillipstanleymarbell** [comment]
@JamesTimothyMeech : Assigning to you.

**Comment by phillipstanleymarbell** [comment]
Fixed in #83 by @JamesTimothyMeech .
