### ISSUE TITLE
BMX055 magnetometer and gyroscope mostly read 0's in the warp datastream

### ISSUE THREAD

**Issue by JamesTimothyMeech** [physical-computation/Warp-firmware#82]
**Describe the bug**
From experience I expect to see more variation in the output of these sensors.

**To reproduce**
Take a look at any file in: https://github.com/physical-computation/Warp-data-stream/tree/master/data

**Expected behavior**
Some random oscillation of values around some non-zero value.

**Comment by phillipstanleymarbell** [comment]
@JamesTimothyMeech : can you verify that this is really a problem?

**Comment by JamesTimothyMeech** [comment]
This does appear to be an issue for the gyro, I will investigate and try to fix it
